### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by loxavia** [agoutsmedt/biblionetwork#3]
Thank you for the great library, I am very enthusiastic about how it could help and the networks I am going to build with it, but one problem is hindering this, is the input format. Would it be possible that it takes a data.frame with vectors of comma separated authors, journals, citations or so on. 
That will be immensely helpful since the data exported from all databases are in this format.

**Comment by agoutsmedt** [comment]
Hi,

Could you be more explicit on this issue? I am not sure to understand where the problem lies. As soon as each citing document and each cited document have a unique id in your data.frame (whether it is an integer identifier or other pieces of information), you should be able to use the functions of our package.

Don't hesitate to submit a reproducible example if you encounter any problems, I would be happy to help.

Best,

Aurélien

**Comment by loxavia** [comment]
Hi, 

Thank you for the reply, I think your library offers a real solution to many problems in bibliometrics  networks, But I just discovered that it requires a special format to work with. I t will beget if it can accept a field or a column from an export file from e.g., Scopus. 
For example taking the Scopus export "Authors" field, one can convert the authors who are listed in that field and separated by ; to a network. That can be used to do many types of networks between funding agencies, keywords, countries and so on.

Looks for example into the file I attached, 

I will be very grateful if you do this step, and I think it open many doors for my research,




[scopus.xlsx](https://github.com/agoutsmedt/biblionetwork/files/6469104/scopus.xlsx)

**Comment by agoutsmedt** [comment]
Which type of network do you want to build? For a co-authorship network, you just need to have one row per author (as each author is a separated node), and the functions in biblionetwork will work perfectly. I am sorry but I can see no limitation in scopus data (that I have also used) that would prevent to use biblionetwork.

Best,

Aurélien

**Comment by loxavia** [comment]
I see, May be share the code that you use to convert colon separated columns into separate rows, or add it to the library ?

**Comment by agoutsmedt** [comment]
You could do it easily using tidyr package, with the [separate()](https://tidyr.tidyverse.org/reference/separate.html) and [pivot_longer()](https://tidyr.tidyverse.org/reference/pivot_longer.html) functions. The first one helps to separate the different authors, the second one puts the different authors in the same column but on different rows, rather than in multiple columns on one row.

**Comment by loxavia** [comment]
I see, this was on my mind, as a solution, I just thought it might be a good idea that this is built into the function. Since, it could help automate things. But then I may probably write this function, to separate, pivot longer, remove loops, and NAs. Thank you !

**Comment by agoutsmedt** [comment]
Yes, I will think about that in a future version but it would imply thinking about all the possible cases and may unnecessarily complexify the function.
Thank you!

Best,

Aurélien
